"""OVON-specific thresholds and prompt/detection defaults."""

from navigation_system.config.core.params.detection import (
    DEFAULT_BOX_THRESHOLD,
    DEFAULT_TEXT_THRESHOLD,
)

OVON_SUCCESS_DISTANCE_M = 0.5
OVON_UNIFIED_NEAR_DISTANCE_M = 0.5
OVON_ARRIVAL_NEAR_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_FINAL_OBJECT_STOP_DISTANCE_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_STRICT_STOP_DISTANCE_M = OVON_FINAL_OBJECT_STOP_DISTANCE_M
OVON_FORCED_EARLY_STOP_DISTANCE_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_FORCED_EARLY_STOP_MAX_DELTA_M = 0.25
OVON_FORCED_EARLY_STOP_THINKING_POINTS = 2

OVON_AUTOCOMPLETE_OPENING_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_AUTOCOMPLETE_SOLID_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_AUTOCOMPLETE_TOPK = 2
OVON_FINAL_OBJECT_LANDMARK_TOPK = 1

OVON_DEFAULT_BOX_THRESHOLD = DEFAULT_BOX_THRESHOLD
OVON_DEFAULT_TEXT_THRESHOLD = DEFAULT_TEXT_THRESHOLD
OVON_TARGET_BOX_THRESHOLD = 0.50
OVON_TARGET_TEXT_THRESHOLD = 0.50
