"""Action-space and motion quantization parameters."""

from .thresholds import (
    AUTOCOMPLETE_OPENING_M,
    AUTOCOMPLETE_SOLID_M,
    AUTOCOMPLETE_TOPK,
)

BASE_TURN_ANGLE_DEG = 30
BASE_MOVE_DISTANCE_M = 0.25
VALID_TURN_DEGREES = (30,)
VALID_MOVE_METERS = (0.25, 0.5, 0.75, 1.0, 1.25)
ACTION_SUBTASK_AUTOCOMPLETE_OPEN_DISTANCE_M = AUTOCOMPLETE_OPENING_M
ACTION_SUBTASK_AUTOCOMPLETE_SOLID_DISTANCE_M = AUTOCOMPLETE_SOLID_M
ACTION_SUBTASK_AUTOCOMPLETE_TOPK = AUTOCOMPLETE_TOPK
