"""Default API client fallbacks."""

DEFAULT_TEMPERATURE = 0.1
DEFAULT_MAX_TOKENS = 2000
DEFAULT_TIMEOUT_S = 60
DEFAULT_IMAGE_COMPRESSION_ENABLED = True
DEFAULT_IMAGE_COMPRESSION_MAX_SIZE = 384
DEFAULT_IMAGE_COMPRESSION_QUALITY = 80
THINKING_IMAGE_COMPRESSION_MAX_SIZE = 640
ACTION_IMAGE_COMPRESSION_MAX_SIZE = 640
ACTION_IMAGE_COMPRESSION_QUALITY = 75

# Pre-layout sizing for model-input images. We resize content first, then add
# prompt-specific white strips so every request keeps a stable visual scale.
THINKING_VIEW_MODEL_CONTENT_WIDTH = 512
ACTION_VIEW_MODEL_CONTENT_WIDTH = 512
GLOBAL_MAP_MODEL_INPUT_SIZE = 440
