"""Spatial reasoning thresholds shared across waypoint/area/view modules."""

DEFAULT_MAP_RESOLUTION_CM = 5
DEFAULT_MAP_SIZE_CM = 2400
DEFAULT_MAP_GLOBAL_DOWNSCALING = 2
DEFAULT_MAP_VISION_RANGE = 100
DEFAULT_MAP_DU_SCALE = 4
DEFAULT_MAP_MIN_Z_CM = 2
DEFAULT_OBSTACLE_MIN_HEIGHT_CM = 15
DEFAULT_OBSTACLE_MAX_HEIGHT_CM = 130
DEFAULT_MAP_EXPLORED_RAY_FILL = False
DEFAULT_MAP_CENTER_RESET_STEPS = 25
DEFAULT_MAX_SEMANTIC_CATEGORIES = 16
DEFAULT_ENABLE_MULTI_FLOOR_TOPOLOGY = True
DEFAULT_STAIR_CLEAR_RADIUS_M = 0.45

CURRENT_AREA_OVERLAP_THRESHOLD_M = 1.0
WAYPOINT_VISIBILITY_RADIUS_M = 1.0
WAYPOINT_VISIBILITY_SAMPLES = 16
WAYPOINT_STRIP_SAME_DIRECTION_GAP_M = 1.0

SPACE_AREA_CONNECTOR_TYPES = {"hallway", "stairs"}
SPACE_AREA_MAX_CONNECTED_AREAS = 3
SPACE_AREA_MAX_CONNECTION_DISTANCE_M = 3.0
SPACE_AREA_MAX_SAME_TYPE_WAYPOINT_MERGE_DISTANCE_M = 5.0
SPACE_AREA_SAME_TYPE_CONNECTOR_SPLIT_DISTANCE_M = 2.0
SPACE_AREA_REGION_RADIUS_M = 2.0
SPACE_AREA_SAMPLE_PIXELS_PER_AREA = 9
SPACE_AREA_CURRENT_WAYPOINT_MAX_DISTANCE_M = 1.25
SPACE_AREA_CURRENT_INITIAL_WAYPOINT_MAX_DISTANCE_M = 1.25
SPACE_AREA_NARROW_PASSAGE_CLEARANCE_M = 0.45
SPACE_AREA_SAME_TYPE_MERGE_MIN_CLEARANCE_M = 0.55

THINKING_DETECTION_TOPK = 2
THINKING_DETECTION_GROUP_MAX_VIEWS = 3
THINKING_DETECTION_TRANSITION_TOTAL_MAX_VIEWS = 4
THINKING_DETECTION_OBJECT_TOTAL_MAX_VIEWS = 2
THINKING_VIEW_HFOV_DEG = 79.0
THINKING_SAME_OBJECT_BEARING_THRESHOLD_DEG = 18.0
THINKING_SAME_OBJECT_DISTANCE_THRESHOLD_M = 0.8
THINKING_SAME_OBJECT_DISTANCE_RATIO = 0.35
