"""OVON-specific thresholds and prompt/detection defaults."""

OVON_SUCCESS_DISTANCE_M = 1.0
OVON_UNIFIED_NEAR_DISTANCE_M = 0.75
OVON_ARRIVAL_NEAR_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_FINAL_OBJECT_STOP_DISTANCE_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_STRICT_STOP_DISTANCE_M = OVON_FINAL_OBJECT_STOP_DISTANCE_M
OVON_FORCED_EARLY_STOP_DISTANCE_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_FORCED_EARLY_STOP_MAX_DELTA_M = 0.25
OVON_FORCED_EARLY_STOP_THINKING_POINTS = 2

OVON_AUTOCOMPLETE_OPENING_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_AUTOCOMPLETE_SOLID_M = OVON_UNIFIED_NEAR_DISTANCE_M
OVON_AUTOCOMPLETE_TOPK = 2

OVON_BOX_THRESHOLD = 0.50
OVON_TEXT_THRESHOLD = 0.50
