"""Action-space and motion quantization parameters."""

BASE_TURN_ANGLE_DEG = 30
BASE_MOVE_DISTANCE_M = 0.25
VALID_TURN_DEGREES = (30,)
VALID_MOVE_METERS = (0.25, 0.5, 0.75, 1.0, 1.25)
ACTION_SUBTASK_AUTOCOMPLETE_OPEN_DISTANCE_M = 0.5
ACTION_SUBTASK_AUTOCOMPLETE_SOLID_DISTANCE_M = 1.0
ACTION_SUBTASK_AUTOCOMPLETE_TOPK = 2
