"""Default API client fallbacks."""

DEFAULT_TEMPERATURE = 0.1
DEFAULT_MAX_TOKENS = 2000
DEFAULT_TIMEOUT_S = 60
DEFAULT_IMAGE_COMPRESSION_ENABLED = True
DEFAULT_IMAGE_COMPRESSION_MAX_SIZE = 384
DEFAULT_IMAGE_COMPRESSION_QUALITY = 80
ACTION_IMAGE_COMPRESSION_MAX_SIZE = 512
ACTION_IMAGE_COMPRESSION_QUALITY = 75
