"""Spatial reasoning thresholds shared across waypoint/area/view modules."""

CURRENT_AREA_OVERLAP_THRESHOLD_M = 1.0
WAYPOINT_VISIBILITY_RADIUS_M = 1.0
WAYPOINT_VISIBILITY_SAMPLES = 16
WAYPOINT_REPLACE_DISTANCE_M = 2.0

SPACE_AREA_CONNECTOR_TYPES = {"hallway", "entryway"}
SPACE_AREA_MAX_CONNECTED_AREAS = 3
SPACE_AREA_MAX_CONNECTION_DISTANCE_M = 3.0
SPACE_AREA_MAX_SAME_TYPE_WAYPOINT_MERGE_DISTANCE_M = 5.0
SPACE_AREA_SAMPLE_PIXELS_PER_AREA = 9
SPACE_AREA_CURRENT_WAYPOINT_MAX_DISTANCE_M = 1.25

THINKING_DETECTION_TOPK = 3
THINKING_DETECTION_GROUP_MAX_VIEWS = 3
THINKING_VIEW_HFOV_DEG = 79.0
THINKING_SAME_OBJECT_BEARING_THRESHOLD_DEG = 18.0
THINKING_SAME_OBJECT_DISTANCE_THRESHOLD_M = 0.8
THINKING_SAME_OBJECT_DISTANCE_RATIO = 0.35
