"""OVON-specific thresholds and prompt/detection defaults."""

OVON_SUCCESS_DISTANCE_M = 1.0
OVON_ARRIVAL_NEAR_M = 0.35

OVON_AUTOCOMPLETE_OPENING_M = 0.25
OVON_AUTOCOMPLETE_SOLID_M = 0.25
OVON_AUTOCOMPLETE_TOPK = 1

OVON_BOX_THRESHOLD = 0.40
OVON_TEXT_THRESHOLD = 0.40
